name: Test grammar & Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-grammar:
    runs-on: ubuntu-latest
    name: Test the grammar
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: actions/setup-node@v4
        name: Set up NodeJS
        with:
          node-version: 18
      - run: npm install
        name: Install dependencies
      - run: npm test
        name: Run tests

  test-package:
    runs-on: ubuntu-latest
    name: Test the Python package
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: 3.8
      - run: pip install -e .
        name: Install dependencies
      - run: test/test_package.py
        name: Run tests
